// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID         uuid.UUID
	FilePath   string
	Repo       string
	CommitHash string
	LineStart  int32
	LineEnd    int32
	Author     string
	Body       string
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	Resolved   sql.NullBool
<<<<<<< HEAD
	UserID     uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.NullUUID
=======
	CharStart  int32
	CharEnd    int32
>>>>>>> 6d1cce4 (work so far in the revision comment program)
}

type User struct {
	ID          uuid.UUID
	GithubID    int64
	Username    string
	Avatar      string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	GithubToken sql.NullString
}
